goplus/llgo

internal/build/build.go, py/python.go, xtool/clang/check/check.go, xtool/env/env.go
Supports alternatives of external library linking.
```LLGoPackage = "link: $LLGO_LIB_PYTHON; $(pkg-config --libs python3-embed); -lpython3"```
=> build: support pkg-config and link args

README.md
```
$ file /opt/homebrew/Frameworks/Python.framework/Versions/3.12/libpython3.12.dylib
/opt/homebrew/Frameworks/Python.framework/Versions/3.12/libpython3.12.dylib: cannot open `/opt/homebrew/Frameworks/Python.framework/Versions/3.12/libpython3.12.dylib' (No such file or directory)
$ file /opt/homebrew/Frameworks/Python.framework/Versions/3.12/lib/libpython3.12.dylib
/opt/homebrew/Frameworks/Python.framework/Versions/3.12/lib/libpython3.12.dylib: Mach-O 64-bit dynamically linked shared library arm64
```
=> README: fix LLGO_LIB_PYTHON instruction

README.md
#312 
More users have encountered the following doubts，Need to update
1. Make it clear that llgo calling non-built-in Python libraries still requires downloading and installing them.
2. Add git clone in the installation step
=> README:update python &  install instructions

internal/build/build.go
We should avoid making any changes to GOROOT whenever possible.
Fixes #361
=> build: set $GOPATH/bin as default GOBIN for Config.BinPath

cl/_testdata/print/out.ll, cl/_testdata/vargs/out.ll, cl/_testgo/equal/out.ll, cl/_testgo/errors/out.ll, cl/_testgo/ifaceprom/out.ll, cl/_testgo/interface/out.ll, cl/_testgo/invoke/out.ll, cl/_testgo/reader/out.ll, cl/_testgo/strucintf/out.ll, cl/_testgo/struczero/out.ll, cl/_testrt/any/out.ll, cl/_testrt/builtin/out.ll, cl/_testrt/eface/out.ll, internal/lib/internal/reflectlite/value.go, internal/runtime/z_face.go, ssa/abitype.go, ssa/interface.go
fix abi for `lib/internal/reflectlite`
- abiType load T before *T
- fix abiMethodOf
=> ssa: fix abiType && abiMethoOf

cl/import.go
fix #435 
Removes the check that only throws an error when a function does not exist.
When using the erroneous example from #435, a warning message will be displayed:
```go
// Should be Lua_State, not Lua_Stage
// llgo:link (*Lua_Stage).PushInteger C.lua_pushinteger
func (L *Lua_State) PushInteger(n Integer) {}
```
Running the code will result in the following warning being correctly output:
```bash
❯ llgo run .
==> // llgo:link (*Lua_Stage).PushInteger C.lua_pushinteger
llgo: linkname (*Lua_Stage).PushInteger not found and ignored
```
=> link:not exist method warning

cl/_testrt/structsize/in.go, cl/_testrt/structsize/out.ll, ssa/type.go
=> fix:correct `Sizeof` to align size properly

c/lua/_demo/coroutine/coroutine.go, c/lua/_demo/error/error.go, c/lua/_demo/funccall-concat/funccall.go, c/lua/_demo/funccall-number/funccall.go, c/lua/_demo/funccall-string/funccall.go, c/lua/_demo/hello/hello.go, c/lua/_demo/loadcall/loadcall.go, c/lua/_demo/stack/stack.go, c/lua/_demo/table/table.go, c/lua/lauxlib.go, c/lua/lua.go, c/lua/lualib.go
For macros, they are also considered to be generated by automated tools, and the naming convention is consistent with that of general functions.
```c
#define lua_tonumber(L,i)	lua_tonumberx(L,(i),NULL)
#define lua_tointeger(L,i)	lua_tointegerx(L,(i),NULL)
#define lua_pop(L,n)		lua_settop(L, -(n)-1)
```
=> llgo/c/lua:link style

internal/build/build.go, xtool/llvm/install_name_tool/rpath.go
```sh
$ otool -L hello
hello:
@rpath/libgc.1.dylib (compatibility version 7.0.0, current version 7.3.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)
$ otool -l hello | grep LC_RPATH -A2
cmd LC_RPATH
cmdsize 32
path @loader_path (offset 12)
--
cmd LC_RPATH
cmdsize 32
path @loader_path/../lib (offset 12)
--
cmd LC_RPATH
cmdsize 56
path /opt/homebrew/Cellar/bdw-gc/8.2.6/lib (offset 12)
--
cmd LC_RPATH
cmdsize 48
path /opt/homebrew/opt/bdw-gc/lib (offset 12)
```
=> build(macOS): change full library paths to @rpath

cl/_testrt/qsortfn/out.ll, cl/_testrt/unsafe/in.go, cl/_testrt/unsafe/out.ll, cl/import.go, internal/build/build.go, internal/llgen/llgen.go, internal/llgen/llgenf.go, internal/packages/load.go, ssa/package.go, ssa/type.go, ssa/type_cvt.go
unsafe.Sizeof 在 types.check 中转换为整数值，所以在 types.check 之前预先分析 []*ast.File 查找 llgo:type C 标志，用来判断 prog.TypesSize.Sizeof 和 prog.gocvt.cvtType 。
- internal/packages
`func (Deduper).SetPreload(fn func(pkg *types.Package, syntax []*ast.File)) `
`func (Deduper).SetPkgPath(fn func(path, name string) string)`
- internal/build
`deduper.SetPreload` for check `llgo:type C` before types.check
- ssa
` (Program).SetTypeBackground(fullName string, bg Background)`
use the `goTypes.typbg` map for types.Sizes and `goTypes.cvtType`
- internal/llgen
use  `internal/packages.Deduper.SetPkgPath` for custome pkgPath.
=> build: fix unsafe.Sizeof for llgo:type C

cl/_testgo/equal/out.ll, cl/_testgo/ifaceconv/out.ll, cl/_testgo/interface/out.ll, cl/_testgo/invoke/out.ll, cl/_testgo/struczero/out.ll, cl/_testrt/abinamed/out.ll, cl/_testrt/eface/out.ll, cl/_testrt/makemap/out.ll, cl/_testrt/typed/out.ll, ssa/abitype.go
fix llc error verified pkg.ll for abiNamed
```
$ llgo build -v .
...
==> Export internal/reflectlite: /Users/my/Library/Caches/go-build/70/706d4eb3d45fb39cc5ffb39a72b0cdb2dcd3882ab2b7db31509a2be1f9d90304-d.ll
...
```
```
$ llc /Users/my/Library/Caches/go-build/70/706d4eb3d45fb39cc5ffb39a72b0cdb2dcd3882ab2b7db31509a2be1f9d90304-d.ll
Instruction does not dominate all uses!
%2 = call ptr @"github.com/goplus/llgo/internal/runtime.NewNamed"(i64 25, i64 24, i64 0, i64 1)
call void @"github.com/goplus/llgo/internal/runtime.InitNamed"(ptr %2, %"github.com/goplus/llgo/internal/runtime.String" %82, %"github.com/goplus/llgo/internal/runtime.String" %86, ptr %38, { ptr, i64, i64 } zeroinitializer, %"github.com/goplus/llgo/internal/runtime.Slice" %78)
Instruction does not dominate all uses!
%2 = call …
```
=> ssa: fix abiNamed for llc verified

cl/_testlibc/demangle/in.go, cl/_testlibc/demangle/out.ll, internal/build/build.go, xtool/env/env.go
fix the issue of clang command errors caused by extra line breaks introduced by `exec.Command(cmd, args[1:]...).Output()`
----
This problematic command has an extra line break.
```
clang [-I/opt/homebrew/Cellar/llvm/18.1.8/include  -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-emit-llvm -S -o /Users/zhangzhiyang/Library/Caches/go-build/56/5656941ebcccc22e088ca01e3b2d684aeba7737dc870cdab6d55dc63162bcb83-d.llcursor.cpp.ll -c /Users/zhangzhiyang/Documents/Code/goplus/llgo/c/clang/_wrap/cursor.cpp]
```
=> env:fix incorrect extra line breaks & subcmd match

c/pthread/sync/sync.go
mismatched function describe in generated ll file against pthread.h
```llvm
declare void @pthread_mutex_lock(ptr)
declare void @pthread_mutex_unlock(ptr) 
```
in pthread.h
```c
int pthread_mutex_lock(pthread_mutex_t *);
int pthread_mutex_unlock(pthread_mutex_t *);
```
So change link lock and unlock to private method and call Lock and Unlock by private method
=> fix describe mismatch in pthread.h

c/setjmp/setjmp.go, c/setjmp/setjmp_linux.go, c/setjmp/setjmp_other.go, internal/build/build.go
1. Handle `sigsetjmp` platform differences:
- Separate `sigsetjmp` linkage to platform-specific files.
- Use `__sigsetjmp` on Linux to handle `sigsetjmp` being a macro.
- Maintain original implementation for Darwin.
2. Ensure linking of required libs:
- Explicitly link against fundamental libs (e.g., libm, libatomic).
- Address the fact that typical Linux linkers don't link these by default.
=> build: fix `sigsetjmp` issues and ensure required libs on Linux

internal/build/build.go
Added `-fdata-sections` and `-ffunction-sections` compiler flags to work with `--gc-sections` on Linux. This combination achieves similar dead code elimination as macOS's `-dead_strip`, reducing binary size and resolving undefined symbol issues. Ensures consistent optimization across macOS and Linux builds.
=> build: replicate macOS `-dead_strip` optimization on Linux

doc/How-to-support-a-C&C++-Library.md
Remove excessive descriptions of visibility and elevate the visibility description to the top of the document.
=> doc/c:refine symbol visibility desc

internal/lib/sync/sync.go
```diff
11d10
< %"github.com/goplus/llgo/internal/runtime.Defer" = type { ptr, i64, ptr, ptr, ptr }
51d49
< @__llgo_defer = linkonce global i32 0, align 4
133,151c131
<   %4 = load i32, ptr @__llgo_defer, align 4
<   %5 = call ptr @pthread_getspecific(i32 %4)
<   %6 = alloca i8, i64 196, align 1
<   %7 = alloca i8, i64 40, align 1
<   %8 = getelementptr inbounds %"github.com/goplus/llgo/internal/runtime.Defer", ptr %7, i32 0, i32 0
<   store ptr %6, ptr %8, align 8
<   %9 = getelementptr inbounds %"github.com/goplus/llgo/internal/runtime.Defer", ptr %7, i32 0, i32 1
<   store i64 0, ptr %9, align 4
<   %10 = getelementptr inbounds %"github.com/goplus/llgo/internal/runtime.Defer", ptr %7, i32 0, i32 2
<   store ptr %5, ptr %10, align 8
<   %11 = getelementptr inbounds …
```
=> perf(lib/sync): avoid using `defer`

c/os/_os/os.c, c/os/os.go, c/os/os_linux.go, c/os/os_other.go
Without `-Xlinker -dead_strip`:
```sh
$ llgo build .
ld64.lld: error: undefined symbol: clearenv
>>> referenced by /var/folders/fh/f39_dzqn0p31th82dvpr1b_w0000gn/T/a7c5a3b89e966e97f2920bb4f709118d21529514a1aac919c229474ffb89c93a-d-6958e0.o:(symbol syscall.Clearenv+0x13c)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
---
The libc on macOS lacks `clearenv`, so this patch adds an implementation.
=> fix(c/os): add missing `clearenv` for macOS

cpp/std/string.go
std::string
```
struct __long
{
pointer   __data_;
size_type __size_;
size_type __cap_;
};
struct __short
{
union
{
unsigned char __size_;
value_type __lx;
};
value_type __data_[__min_cap];
};
```
=> cpp/std: fix std::string def

c/clang/_demo/symboldump/symboldump.go, c/clang/clang.go
Fixed macro content output incompleteness caused by incorrect address passing in value methods. Macro content is now displaying fully, including previously missing operators and symbols.
```bash
#define MAX(a, b) ((a) > (b) ? (a) : (b))
#define ABS(x) ((x) < 0 ? -(x) : (x))
#define COMPUTE(x, y) (MAX(ABS(x), ABS(y)))
```
```bash
./test.h:19:9
Marco Name: MAX
Content: MAX ( a , b ) ( ( a ) > ( b ) ? ( a ) : ( b ) )
--------------------------------
./test.h:20:9
Marco Name: ABS
Content: ABS ( x ) ( ( x ) < 0 ? - ( x ) : ( x ) )
--------------------------------
./test.h:21:9
Marco Name: COMPUTE
Content: COMPUTE ( x , y ) ( MAX ( ABS ( x ) , ABS ( y ) ) )
--------------------------------
```
=> c/clang:marco content

c/libuv/_demo/async_fs/async_fs.go, c/libuv/_demo/echo_server/echo_server.go, c/libuv/_wrap/libuv.c, c/libuv/fs.go, c/libuv/libuv.go, c/libuv/net.go, c/libuv/signal.go
Signed-off-by: hackerchai <i@hackerchai.com>
=> feat(c/libuv): Add libuv missing funcs & refactor go func style

c/clang/_wrap/cursor.cpp, c/clang/clang.go, chore/_xtool/castdump/castdump.go
1. For nodes with types, their type trees are recursively output. Currently supported types include array, typedef, pointer, funcproto, enum, and builtin types.
2. For enum types, although they are complex types, it's not possible to obtain their more fundamental underlying 
types. 
```
ClassDecl: INIReader(Loc:/opt/homebrew/Cellar/inih/58/include/INIReader.h:42:7)
<ComplexType|Record>: INIReader
CXXAccessSpecifier:  public(Loc:/opt/homebrew/Cellar/inih/58/include/INIReader.h:43:3)
CXXConstructor: INIReader (Symbol: __ZN9INIReaderC1ERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE)(Loc:/opt/homebrew/Cellar/inih/58/include/INIReader.h:46:22)
<ComplexType|FunctionProto>: void (const std::string &)
<ComplexType|LValueReference>: const std::string &
attribute(visibility): …
```
=> castdump:array,typedef,pointer,funcproto,enum & builtin type

c/clang/_wrap/cursor.cpp, c/clang/clang.go, chore/_xtool/castdump/castdump.go
```
ClassDecl: INIReader(Loc:/opt/homebrew/Cellar/inih/58/include/INIReader.h:42:7)
<ComplexType|Record>: INIReader
CXXAccessSpecifier:  public(Loc:/opt/homebrew/Cellar/inih/58/include/INIReader.h:43:3)
CXXConstructor: INIReader (Symbol: __ZN9INIReaderC1ERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE)(Loc:/opt/homebrew/Cellar/inih/58/include/INIReader.h:46:22)
<ComplexType|FunctionProto>: void (const std::string &)
<BuiltinType|Void>: void
<ComplexType|LValueReference>: const std::string &
attribute(visibility): default
ParmDecl: filename(Loc:/opt/homebrew/Cellar/inih/58/include/INIReader.h:46:51)
<ComplexType|LValueReference>: const std::string &
NamespaceRef: std
TypeRef: std::string(Loc:/opt/homebrew/Cellar/inih/58/include/INIReader.h:46:43)
<ComplexType|Typedef>: …
```
=> castdump:funcproto type & computed enum value

py/tuple.go
Works as expected:
```go
package main
import (
"github.com/goplus/llgo/py"
"github.com/goplus/llgo/py/std"
)
func main() {
t := py.NewTuple(3)
t.TupleSetItem(0, py.Str("111"))
t.TupleSetItem(1, py.Str("222"))
t.TupleSetItem(2, py.Str("333"))
std.Print(t)
s := t.TupleSlice(1, 3)
std.Print(s)
}
```
```
$ ./llgo build -o a a.go
$ ./a 
('111', '222', '333')
('222', '333')
```
=> feat(py): Add more method to tuple object

cl/_testpy/max/in.go, cl/_testpy/max/out.ll, cl/import.go, cl/instr.go, py/tuple.go, ssa/package.go, ssa/python.go
Add a `py.Tuple` constructor which is similar to the exist `py.List`. Usage:
```
package main
import (
"github.com/goplus/llgo/py"
"github.com/goplus/llgo/py/std"
)
func main() {
t := py.Tuple(py.Str("foo"), py.Str("bar"), py.Str("baz"))
std.Print(t)
}
```
```
$ ./llgo build -o a a.go
$ ./a 
('foo', 'bar', 'baz')
```
=> feat(py): Add Python tuple constructor helper

_demo/mkdirdemo/mkdir.go
```bash
❯ llgo run .                  
Temp directory: /var/folders/5j/sgtxqmbn1hbdqtgx5kkp6y700000gn/T/example627607814
Temp file: /var/folders/5j/sgtxqmbn1hbdqtgx5kkp6y700000gn/T/example1912339481.txt
Nest directory 3: /var/folders/5j/sgtxqmbn1hbdqtgx5kkp6y700000gn/T/example627607814
```
Currently `os.MkdirAll` still has problems creating nested folders https://github.com/goplus/llgo/issues/713
=> lib/os:mkdir demo

c/pthread/_pthread/pthread_gc.c, c/pthread/_pthread/pthread_nogc.c, c/pthread/pthread.go, c/pthread/pthread_gc.go, c/pthread/pthread_nogc.go, cl/_testgo/goroutine/out.ll, ssa/goroutine.go
- Use `GC_pthread_create` instead of `pthread_create` when GC is enabled.
=> gc: fix missing pthread registration causing unknown thread error

chore/llcppg/ast/ast.go
* remove complex, it's more likely an expr;
*  not concern with Objective-C,Accum,IBM128,BFloat16,  it's not part of standard C or C++
| Type                 | TypeFlag             | TypeKind |
| -------------------- | -------------------- | -------- |
| CXType\_Void         |                      | Void     |
| CXType\_Bool         |                      | Bool     |
| CXType\_Char\_U      | Unsigned             | Char     |
| CXType\_UChar        | Unsigned             | Char     |
| CXType\_Char16       |                      | Char16          |
| CXType\_Char32       |                      |  Char32        |
| CXType\_UShort       | Unsigned \| Short    | Int      |
| CXType\_UInt         | Unsigned             | Int      |
| CXType\_ULong        | Unsigned \| Long     | Int      |
| …
=> llcppg/ast:builtin type

chore/llcppg/ast/ast.go
To Describe  a  `Fully Qualified Name Declaration with Struct Tag`,like follow
```c++
struct outer::inner::MyStruct s;
```
```
&TagExpr{
Tag: Struct,
Name: &ScopingExpr{
Parent: &Ident{Name: "outer"},
X: &ScopingExpr{
Parent: &Ident{Name: "inner"},
X: &Ident{Name: "MyStruct"},
},
},
}
```
=> llcppg/ast:scoping for Tagexpr

py/set.go
Test case:
```go
package main
import (
"github.com/goplus/llgo/py"
"github.com/goplus/llgo/py/std"
)
func main() {
t := py.Tuple(py.Str("foo"), py.Str("bar"))
std.Print(t)
s := py.NewSet(t)
s.SetAdd(py.Str("baz"))
std.Print(s)
println(s.SetLen())
println(s.SetContains(py.Str("foo")))
s.SetPop()
std.Print(s)
s.SetClear()
std.Print(s)
}
```
Result:
```
$ ./llgo build -o a a.go
$ ./a 
('foo', 'bar')
{'foo', 'bar', 'baz'}
3
1
{'bar', 'baz'}
set()
```
=> feat(py): add set type

chore/_xtool/castdump/castdump.go
```cpp
typedef struct A {
int x;
} *MyStruct;
```
```Diff
StructDecl: A(Loc:./a.h:1:16)
<ComplexType|Record>: A
FieldDecl: x(Loc:./a.h:2:9)
<BuiltinType|Int>: int
TypedefDecl: MyStruct(Loc:./a.h:3:4)
<ComplexType|Typedef>: MyStruct
-     <ComplexType|Pointer>: A *
-        <ComplexType|Record>: A
+     <ComplexType|Pointer>: struct A *
+        <ComplexType|Elaborated>: struct A
+           <ComplexType|Record>: A
StructDecl: A(Loc:./a.h:1:16)
<ComplexType|Record>: A
FieldDecl: x(Loc:./a.h:2:9)
<BuiltinType|Int>: int
```
在更新之前，对于Typedef是使用CanonicalType获得原始类型的，该类型即是Typedef 对应的UnderlyingType  Desugar后的类型，而在libclang的树中，应该使用UnderlyingType访问Typedef对应的类型。
对于一个复杂类型的引用会保留 elaborated类型，该类型保留了引用复杂类型时的信息，比如对于一个声明的结构体，可以区分是通过struct a引用，还是直接通过 a 名称引用  
```
/**
* Return the canonical type for a CXType. …
```
=> castdump:use UnderlyingType instead CanonicalType in typedef

cl/_testrt/tpfunc/in.go, cl/_testrt/tpfunc/out.ll, ssa/package.go, ssa/type.go, ssa/type_cvt.go
fix llgo:type c for typeparams
```
package main
import (
"unsafe"
)
type Func func(*int)
//llgo:type C
type CFunc func(*int)
//llgo:type C
type Callback[T any] func(*T)
func main() {
var fn1 Func = func(v *int) {
println(*v)
}
var fn2 CFunc = func(v *int) {
println(*v)
}
var fn3 Callback[int] = func(v *int) {
println(*v)
}
println(unsafe.Sizeof(fn1), unsafe.Sizeof(fn2), unsafe.Sizeof(fn3))
}
```
=> ssa: fix llgo:type c for typeparam named

cl/_testrt/tpabi/out.ll, cl/_testrt/tpmethod/in.go, cl/_testrt/tpmethod/out.ll, cl/compile.go
fix https://github.com/goplus/llgo/issues/779
=> cl: processPkg check runtimeTypes for generic method

cl/_testgo/equal/out.ll, cl/_testgo/ifaceprom/out.ll, cl/_testgo/interface/out.ll, cl/_testgo/invoke/out.ll, cl/_testgo/reader/out.ll, cl/_testgo/selects/out.ll, cl/_testgo/strucintf/out.ll, cl/_testgo/struczero/out.ll, cl/_testgo/tptypes/out.ll, cl/_testrt/abinamed/out.ll, cl/_testrt/index/out.ll, cl/_testrt/makemap/out.ll, cl/_testrt/slice2array/out.ll, cl/_testrt/struct/out.ll, cl/_testrt/tpabi/out.ll, cl/_testrt/tpmethod/out.ll, cl/_testrt/typed/out.ll, internal/runtime/z_rt.go, ssa/memory.go, ssa/package.go
The `runtime.Zeroinit` function isn't compatible with `ssa.NaiveForm` mode (fully disable SSA optimizations for debugging), because the compiler will generate recursive code.
Another reason is that in the disassembly code, `runtime.Zeroinit` isn't inlined; it calls the C function `_memset`. These should be replaced with the `LLVM memset intrinsic` and be compiled to inlined code. See https://llvm.org/docs/LangRef.html#llvm-memset-intrinsics
`c.Memset` maybe also need to be replaced with an `llgo:link` instruction to rewrite it to the `memset intrinsic`.
Test code:
```go
type E struct {
}
type F struct {
e *E
i int
f float64
}
func Bar() {
f := F{e: &E{}}
println(f.e)
}
```
Before:
```llvm
define void @main.Bar() {
_llgo_0:
%0 = alloca %main.F, align 8
%1 = call ptr …
```
=> Use LLVM memset intrinsic for compatibility and performance

chore/_xtool/llcppsymg/clangutils/clangutils.go, chore/_xtool/llcppsymg/llcppsymg.go, chore/_xtool/llcppsymg/parse/parse.go
* 将`llcppsymg.symb.json`的函数原型输出修改为通过libclang中获得头文件中函数签名以及向上递归语法父级来构建，之前的实现方式是通过`manglename`直接`demangle`来获取的函数签名，但这个形式输出的内容实际上并不易读，比如一个 `const std:string &`,会输出为` std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&`,对于使用该工具的用户来说，并不直观
**C++**
```json
{
"mangle": "_ZN9INIReader12ValueHandlerEPvPKcS2_S2_",
"c++": "INIReader::ValueHandler(void*, char const*, char const*, char const*)",
"go": "(*Reader).ValueHandler"
},
{
"mangle": "_ZN9INIReader7MakeKeyERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_",
"c++": "INIReader::MakeKey(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)",
"go": …
```
=> llcppsymg:parse c / c++ &  output  func proto

cl/_testgo/equal/out.ll, cl/_testgo/errors/out.ll, cl/_testgo/ifaceconv/out.ll, cl/_testgo/ifaceprom/out.ll, cl/_testgo/interface/out.ll, cl/_testgo/invoke/out.ll, cl/_testgo/reader/out.ll, cl/_testgo/struczero/out.ll, cl/_testrt/abinamed/out.ll, cl/_testrt/eface/out.ll, cl/_testrt/makemap/out.ll, cl/_testrt/tpabi/out.ll, cl/_testrt/tpmethod/out.ll, cl/_testrt/typed/out.ll, internal/abi/type.go, internal/lib/reflect/type.go, internal/lib/reflect/value.go, internal/runtime/z_face.go, ssa/abi/abi.go, ssa/abitype.go, ssa/package.go
internal/lib/reflect
- Value.Pointer
- Type.Name
- Type.NumMethod
- Type.Method
- Type.MethodByName
- Type.Field
- Type.FieldByIndex
- Type.FieldByName
- Type.FieldByNameFunc
- Type.PtrTo 
- FuncOf
TODO
`typesByString` not impl
=> [wip] lib reflect

chore/llcppg/ast/ast.go
In C header files, this is not mangled and matches the Name. In C++, it's mangled according to C++ name mangling rules.
=> llcppg/ast:func mangle name

py/call.go
Test:
```go
package main
import (
"fmt"
"github.com/goplus/llgo/c"
"github.com/goplus/llgo/py"
)
func main() {
py.Initialize()
py.SetProgramName(*c.Argv)
code := py.CompileString(c.Str(`print('Hello, World!')`), c.Str(`hello.py`), py.EvalInput)
fmt.Printf("code: %p\n", code)
}
```
Compile:
```shell
ld64.lld: error: undefined symbol: PyObject_CallMethodOneArg
>>> referenced by /var/folders/f2/88rgt2bx533_m89qy6pqqp8w0000gn/T/47fbbe34e8445e113519eece8f659d08212a2f24496f75d8225b90b3cc8c6a0b-d-abff41.o:(symbol main.init$after+0x17ac)
>>> referenced by /var/folders/f2/88rgt2bx533_m89qy6pqqp8w0000gn/T/47fbbe34e8445e113519eece8f659d08212a2f24496f75d8225b90b3cc8c6a0b-d-abff41.o:(symbol main.init$after+0x17a8)
ld64.lld: error: undefined symbol: PyObject_CallMethodNoArgs
>>> referenced by …
```
=> py: remove static methods

internal/lib/syscall/syscall.go
#825 
current  patch in llgo only returns 0 and -1. The value -1 is not the appropriate return value for file errors
The panic was in the use `os.Errno`.
in the generate ir in llgo like this demo.
```llvm
; ModuleID = 'errno'
source_filename = "errno"
@errno = external global i32, align 4
declare i32 @putchar(i32)
define i32 @main() {
entry:
%0 = load i32, ptr @errno, align 4
%1 = add i32 %0, 48  ; Convert to ASCII digit (assuming errno is 0-9)
call i32 @putchar(i32 %1)
call i32 @putchar(i32 10)  ; Print newline
ret i32 0
}
```
will cause follow error
```bash
/usr/bin/ld: errno: TLS definition in /lib/aarch64-linux-gnu/libc.so.6 section .tbss mismatches non-TLS reference in demo.o
/usr/bin/ld: /lib/aarch64-linux-gnu/libc.so.6: error adding symbols: bad value
clang: error: linker command …
```
=> [wip] os:correct error of noexist file & os.Error 's nil pointer dereference in linux

chore/nmdump/nmdump.go, xtool/nm/nm.go
#830 
* support pass flag
* parse symbol version for linux 
For llcppsymg  get dynamic symbol in linux by passing option to `nm`.
before havent symbol output
```bash
root@be00d9b1c2c9:/lib/aarch64-linux-gnu# nmdump liblua5.4.so
root@be00d9b1c2c9:/lib/aarch64-linux-gnu# 
```
after,pass -D flag can outout dynamic symbol normally
```
root@be00d9b1c2c9:/lib/aarch64-linux-gnu# nmdump -D liblua5.4.so
0000000000000000 A LUA_5.4@@LUA_5.4
w _ITM_deregisterTMCloneTable
w _ITM_registerTMCloneTable
U __ctype_b_loc@GLIBC_2.17
U __ctype_tolower_loc@GLIBC_2.17
U __ctype_toupper_loc@GLIBC_2.17
w __cxa_finalize@GLIBC_2.17
U __errno_location@GLIBC_2.17
U __fprintf_chk@GLIBC_2.17
w __gmon_start__
```
=> xtool/nm:flags option & symbol version

cl/_testrt/funcaddr/in.go, cl/_testrt/funcaddr/out.ll, cl/instr.go
c.Func support typec funclit
```
package main
import (
"unsafe"
"github.com/goplus/llgo/c"
)
//llgo:type C
type Add func(int, int) int
func add(a, b int) int {
return a + b
}
func main() {
var fn Add = add
var myfn Add = func(a, b int) int {
return a + b
}
println(c.Func(add) == c.Func(fn))
println(c.Func(fn) == *(*unsafe.Pointer)(unsafe.Pointer(&fn)))
println(c.Func(myfn) == *(*unsafe.Pointer)(unsafe.Pointer(&myfn)))
}
```
=> cl: instr funcAddr support typec funclit

_demo/checkfile/demo.go, c/os/_os/os.c, c/os/os.go, c/os/os_linux.go, internal/build/_overlay/net/textproto/textproto.go, internal/lib/os/os.go, internal/lib/os/types.go, internal/lib/syscall/exec_libc2.go, internal/lib/syscall/syscall.go, internal/lib/syscall/syscall_bsd.go
fix #825 
The panic was in the use `os.Errno`.
in the generate ir in llgo like this demo.
```llvm
; ModuleID = 'errno'
source_filename = "errno"
@errno = external global i32, align 4
declare i32 @putchar(i32)
define i32 @main() {
entry:
%0 = load i32, ptr @errno, align 4
%1 = add i32 %0, 48  ; Convert to ASCII digit (assuming errno is 0-9)
call i32 @putchar(i32 %1)
call i32 @putchar(i32 10)  ; Print newline
ret i32 0
}
```
will cause follow error
```bash
/usr/bin/ld: errno: TLS definition in /lib/aarch64-linux-gnu/libc.so.6 section .tbss mismatches non-TLS reference in demo.o
/usr/bin/ld: /lib/aarch64-linux-gnu/libc.so.6: error adding symbols: bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
we can see the marcos define the errno is actually …
=> os:fix os.Errno 's nil pointer derefer in linux

cl/_testgo/constconv/in.go, cl/_testgo/constconv/out.ll, ssa/expr.go
```go
func main() {
var i64 int64 = 1
var u64 uint64 = 1
var c int64 = i64 + (1.0 / (1.0 / 10))
var d uint64 = u64 + (1.0 / (1.0 / 10))
println(u64, i64, c, d)
}
```
Compiles error:
```
panic: 10 not an Int
```
=> ssa: fix int constant type conversion

.github/workflows/go.yml, .gitignore, _lldb/common.sh, _lldb/llgo_plugin.py, _lldb/runlldb.sh, _lldb/runtest.sh, _lldb/test.py, chore/llgen/llgen.go, cl/_testdata/debug/in.go, cl/compile.go, cl/instr.go, internal/build/build.go, internal/llgen/llgen.go, internal/llgen/llgenf.go, ssa/decl.go, ssa/di.go, ssa/eh.go, ssa/stmt_builder.go, ssa/type_cvt.go
- discuz:
- https://stackoverflow.com/questions/79023513/whats-wrong-in-my-generated-debug-info-in-llvm-ir
- https://chat.stackoverflow.com/rooms/258538/discussion-between-jmmartinez-and-jacky-lee
- just use simple rules, and ignore discarded debug info of clang
=> Debug: fix struct vars debug, params modication, supports expressions, lexical scope/lifecycle

cl/_testgo/selects/out.ll, cl/_testrt/closureiface/in.go, cl/_testrt/closureiface/out.ll, cl/cltest/cltest.go, cl/compile_test.go, ssa/di.go, ssa/expr.go, ssa/type_cvt.go
- fix closure type
```
var m int = 200
fn := func(n int) int {
return m + n
}
```
```
Do 0 make closure main$1 [t0] [100:int]
Call 10 struct{f func(__llgo_ctx unsafe.Pointer, __llgo_ctx *struct{m *int}, n int) int; data unsafe.Pointer} closure: i64 100
```
fixed type to
```
Do 0 make closure main$1 [t0] [100:int]
Call 10 struct{f func(__llgo_ctx unsafe.Pointer, n int) int; data unsafe.Pointer} closure: i64 100
```
- fix closure conv
```
func main() {
var m int = 200
fn := func(n int) int {
return m + n
}
var i any = fn
f, ok := i.(func(int) int)
if !ok {
panic("error")
}
println(f(100))
}
```
=> ssa: fix closure type

_demo/async/async/async.go, _demo/async/main.go, _demo/async/timeout/timeout.go, cl/_testgo/syncmap/in.go, cl/_testgo/syncmap/out.ll, cl/_testgo/tprecurfn/in.go, cl/_testgo/tprecurfn/out.ll, cl/_testrt/abinamed/out.ll, cl/_testrt/tpmap/in.go, cl/_testrt/tpmap/out.ll, cl/builtin_test.go, cl/compile.go, internal/lib/sync/map.go, internal/lib/sync/sync.go, ssa/type_cvt.go
- ssa: fix goTypes.cvtNamed recurs for typeargs
- ssa: fix map key has typeargs ( in struct )
- internal/lib/sync: support sync.Map
=> ssa: fix gocvt named recurs for typeargs. support sync.Map

c/clang/_demo/inclusion/inclusion.go, c/clang/clang.go
below problem resolved in PR #850
During the development process, a bug (#848) was discovered that causes incorrect iteration over a slice formed from a non-existent include stack when traversing the include stack. 
```bash
clang/_demo/inclusion on  c/clang/visitinclude [$!?] via 🐹 v1.20.4 
❯ llgo run .
Included file: temp.h Include length: 0
panic: runtime error: invalid memory address or nil pointer dereference
```
=> c/clang:include

c/clang/_demo/inclusion/inclusion.go
after #848, redundant null checks can be removed
=> c/clang:demo common iterate

.github/workflows/go.yml
If libffi's PKG_CONFIG_PATH is not set for Homebrew-installed libffi, the llgo-compiled llcppsigfetch program fails to execute due to missing libffi.dylib dependency.
https://github.com/luoliwoshang/llgo/actions/runs/11679357457/job/32520313633
```bash
=== RUN   TestSigfetch/cpp_sigfetch
symb_test.go:72: error running llcppsigfetch: signal: abort trap
Stderr: dyld[7125]: Library not loaded: @rpath/libffi.dylib
Referenced from: <4C4C443F-5555-3144-A1F4-363ACED773AF> /Users/runner/go/bin/llcppsigfetch
Reason: tried: '/Users/runner/go/bin/libffi.dylib' (no such file), '/Users/runner/go/bin/../lib/libffi.dylib' (no such file), '/opt/homebrew/Cellar/cjson/1.7.18/lib/libffi.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/cjson/1.7.18/lib/libffi.dylib' (no such …
```
=> workflow:libffi

chore/_xtool/llcppsigfetch/parse/cvt.go, chore/_xtool/llcppsigfetch/parse/cvt_test/cvt.go, chore/_xtool/llcppsigfetch/parse/cvt_test/decl_test/typedef_test/llgo.expect, chore/_xtool/llcppsigfetch/parse/cvt_test/decl_test/typedef_test/typedef.go, chore/_xtool/llcppsigfetch/parse/cvt_test/preprocess_test/llgo.expect, chore/_xtool/llcppsigfetch/parse/cvt_test/preprocess_test/preprocess.go, chore/_xtool/llcppsigfetch/parse/cvt_test/preprocess_test/testdata/macroexpan/def.h, chore/_xtool/llcppsigfetch/parse/cvt_test/preprocess_test/testdata/macroexpan/ref.h
Fix  https://github.com/luoliwoshang/llgo/issues/78
解决在Linux下引入stdlib.h后出现的  index out of range panic。
一个宏定义在另外一个头文件中，当头文件其中一个类型引用后，可以获得其Underlying类型，但是为了判断其实际的匿名性质，访问其定义节点，对其Token序列化，返回Token序列为空，导致无法通过Token序列获取其实际的匿名性质。
最小复现https://github.com/goplus/llgo/blob/069760541c2c7092cc39df5c66b62381740654aa/chore/_xtool/llcppsigfetch/parse/cvt_test/preprocess_test/preprocess.go#L45
`fsid.h`
```c
#define __FSID_T_TYPE struct {  int __val[2]; }
```
`typedef.h`
```c
#include "fsid.h"
typedef __FSID_T_TYPE NewType;
```
对于这个类型声明节点，其range 仍然为原始宏名称的开始和结束的位置.
https://github.com/luoliwoshang/CTest/commit/d564aa5b4d1e94ef96c8e5d62241ecf58f9f3a8c
```bash
underlying type: struct NewType
type declaration: NewType
type declaration kind: StructDecl
range start: 2:9, range end: 2:22
```
Libclang …
=> llcppsigfetch:typedef refer same struct & remove tokenize check for underlying

_demo/cgodefer/cgodefer.go, _demo/reflectfunc/reflectfunc.go, cl/_testgo/closure2/in.go, cl/_testgo/closure2/out.ll, ssa/type_cvt.go
Fix https://github.com/goplus/llgo/issues/864 (call closure failed)
Fix https://github.com/goplus/llgo/issues/832 (wrong reflect type of closure):
```shell
➜  llgo git:(fix-closure) ✗ go run ./_demo/reflectfunc
func(int, int) int
func
func(int, int) int
func
➜  llgo git:(fix-closure) ✗ go run ./cmd/llgo run ./_demo/reflectfunc
ld: warning: -ld_classic is deprecated and will be removed in a future release
func(...)
func
func(...)
func
```
=> ssa: fix wrong reflect type of closure

_demo/syncdebug/syncdebug.go, cl/compile.go, ssa/package.go, ssa/type.go
Fix https://github.com/goplus/llgo/issues/877
```go
package main
import (
"io"
"os"
"sync"
"unsafe"
llsync "github.com/goplus/llgo/c/pthread/sync"
)
type L struct {
mu sync.Mutex
s  string
i  int
w  io.Writer
}
func main() {
l := &L{s: "hello", i: 123, w: os.Stdout}
println("sizeof(L):", unsafe.Sizeof(L{}))
println("sizeof(sync.Mutex):", unsafe.Sizeof(sync.Mutex{}))
println("sizeof(llsync.Mutex):", unsafe.Sizeof(llsync.Mutex{}))
println("l:", l, "l.s:", l.s, "l.i:", l.i, "l.w:", l.w)
l.mu.Lock()
println("locked")
println("l:", l, "l.s:", l.s, "l.i:", l.i, "l.w:", l.w)
l.w.Write([]byte(l.s))
l.w.Write([]byte("\n"))
l.mu.Unlock()
}
```
Outputs on macOS arm64:
```shelll
sizeof(L): 48
sizeof(sync.Mutex): 8
sizeof(llsync.Mutex): 64
l: 0x102649a10 l.s: hello l.i: 123 l.w: …
```
=> Fix type patching

.github/workflows/go.yml, internal/build/cgo.go, internal/lib/syscall/syscall_linux.go
=> Enable demo test

cl/_testgo/invoke/out.ll, cl/_testgo/reflect/in.go, cl/_testgo/reflect/out.ll, cl/_testrt/abinamed/out.ll, cl/_testrt/closureiface/out.ll, cl/_testrt/eface/out.ll, cl/_testrt/funcdecl/out.ll, cl/_testrt/tpabi/out.ll, cl/_testrt/tpmethod/out.ll, internal/abi/type.go, internal/lib/reflect/makefunc.go, internal/lib/reflect/type.go, internal/lib/reflect/value.go, ssa/abitype.go, ssa/decl.go, ssa/expr.go, ssa/type.go, ssa/type_cvt.go
- ssa: cvtFunc keep signature org variadic. ( toLLVMFunc variadic by NameValist )
- ssa: cvtClosure remove closureCtx param
- internal/abi: fix  abi.Type.NumMethod
- internal/lib/reflect: call variadic check
=> ssa: closure use org signature

.github/workflows/populate_darwin_sysroot.sh
Test build: https://github.com/cpunion/llgo/actions/runs/12077809222
Test release: https://github.com/cpunion/llgo/releases/tag/v0.9.27
=> ci: lock release build to llvm@18

c/c.go
fix https://github.com/goplus/llcppg/issues/46
=> include/_types: add Uint8T, Uint16T, Uint32T, Uint64T, IntmaxT, UintmaxT

cl/_testgo/ifaceconv/out.ll, cl/_testgo/ifaceprom/out.ll, cl/_testgo/interface/out.ll, cl/_testgo/invoke/out.ll, cl/_testgo/reader/out.ll, cl/_testrt/tpmethod/out.ll, internal/runtime/z_face.go, ssa/abitype.go
fix named interface init.
```
fix internal/reflectlite.Type imethod incorrect if recursion ( eg. Implements(u Type) bool )
fix named interface with abi.TFlagNamed | abi.TFlagUncommon
```
=> abi: fix named interface init

cl/_testrt/eface/in.go, cl/_testrt/eface/out.ll, cl/_testrt/typed/out.ll, ssa/expr.go
fix const type for named string
```
type T string
var v any = T("hello")
println(v.(T)) // panic: type assertion failed
```
=> ssa: fix const for named string

cl/_testgo/invoke/out.ll, cl/_testgo/reflect/in.go, cl/_testgo/reflect/out.ll, cl/_testrt/abinamed/out.ll, cl/_testrt/closureiface/out.ll, cl/_testrt/eface/out.ll, cl/_testrt/funcdecl/out.ll, cl/_testrt/tpmethod/out.ll, internal/lib/reflect/makefunc.go, internal/runtime/z_face.go, internal/runtime/z_type.go, ssa/interface.go, ssa/type.go, ssa/type_cvt.go
closure struct `{ f ftype, data unsafe.Pointer}` => `{ $f ftype, $data unsafe.pointer }`
abi.StructType check closure  ( abi.TFlagClosure ) ignore .PkgPath_
=> ssa: closure use specific struct field name

cl/_testrt/float2any/in.go, cl/_testrt/float2any/out.ll, ssa/interface.go
fix float32 to any bitcast
```
package main
const pi = 3.14159265
func check32(v any) {
if v.(float32) != pi {
panic("error f32")
}
}
func f32() float32 {
return pi
}
func main() {
check32(f32())
}
```
```
invalid cast opcode for cast from 'float' to 'i64'
122 |   %4 = bitcast float %2 to i64
```
=> ssa: fix bitcast for float32

.github/workflows/go.yml, README.md, _demo/failed/stacktrace/main.go, c/debug/_wrap/debug.c, c/debug/debug.go, doc/_readme/scripts/install_ubuntu.sh, internal/runtime/z_rt.go
```
go run ./cmd/llgo run ./_demo/failed/stacktrace
ld: warning: -ld_classic is deprecated and will be removed in a future release
In generic method
In generic function
In normal function
panic: panic occurs here
[0x0271D310 github.com/goplus/llgo/internal/runtime.Rethrow+0x2f, SP = 0x60]
[0x0271CF44 github.com/goplus/llgo/internal/runtime.Panic+0x2d, SP = 0x50]
[0x02719420 main.normalFunc+0xf, SP = 0xa8]
[0x02719564 main.genericFunc[string]+0x18, SP = 0x74]
[0x027194A8 main.(*MyStruct[string]).Method+0x1f, SP = 0x84]
[0x0271936C main+0x4, SP = 0x40]
exit status 2
```
=> runtime: show stacktrace when panic

internal/build/build.go, internal/env/env.go
Fix: https://github.com/goplus/llgo/issues/892 https://github.com/goplus/llgo/issues/651, need update release distribution and installation to use it.
Supports:
- env LLGO_ROOT: set to llgo root dir that can find go.mod contains `module github.com/goplus/llgo\n`
- Directory that contains the executable in `bin/`, and also has go.mod contains `module github.com/goplus/llgo\n`
- Will support `go build -ldflags "-X github.com/goplus/llgo/compiler/internal/env.LLGO_ROOT=/path/to"` after separate compiler and library
And it will support separation runtime/patches from llgo library.
=> env: allow compiling code outside llgo directory

internal/build/build.go
Before:
```shell
➜  _demo git:(main) ✗ go run ../cmd/llgo build ./async ./hello
ld: warning: -ld_classic is deprecated and will be removed in a future release
build flags: [-tags llgo]
patterns: [-tags llgo]
-: malformed import path "-tags": leading dash
cannot build SSA for package -tags
-: package llgo is not in GOROOT (/opt/homebrew/Cellar/go@1.20/1.20.14/libexec/src/llgo)
cannot build SSA for package llgo
exit status 1
```
After:
```shell
➜  _demo git:(fix-build) ✗ go run ../cmd/llgo build ./async ./hello
ld: warning: -ld_classic is deprecated and will be removed in a future release
build flags: [-tags llgo]
patterns: [./async ./hello]
```
=> build.ParseArgs returns new slices to fix wrong patterns with flags appending

README.md
User may not install pkg-config when initalization.
When lacking of pkg-config tool, it will panic like that 
```
panic: test link args ' $(pkg-config --libs bdw-gc); -lgc' failed
expanded to: [-lgc]
resolved to: [-lgc]
error: ld: library 'gc' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
=> README: fix dependences requirement for macOS

compiler/cl/compile.go, compiler/ssa/abitype.go, compiler/ssa/package.go
Fix https://github.com/goplus/llgo/issues/947
- Skip ABI generation for uninstantiated generic methods
Maybe a better way is refactoring ABI generation based on type/func compilation.
=> fix(ssa): fix incorrectly ABI for uninstantiated generic methods

compiler/ssa/abitype.go, compiler/ssa/type.go, compiler/ssa/type_cvt.go
- fix cvtType for go1.22/1.23 `GODEBUG=gotypesalias=1`
- fix compiler build for go1.22 `GODEBUG=gotypesalias=1`
=> ssa: fix cvtType check types.Alias

.github/workflows/go.yml, compiler/cl/compile_test.go, compiler/ssa/cl_test.go
- reset test default actions for ci/ssa
- ci go test remove -v
=> ci: go test remove -v

c/clang/_demo/symboldump/symboldump.go, c/clang/_wrap/cursor.cpp, c/clang/clang.go
`main.h`
```c
#define foo 1
typedef struct A {
long a;
char d[foo];
} A;
#include "compat.h"
typedef B C;
```
compat.h
```c
typedef A B;
```
`clang -dD -E -C -x c-header main.h > temp.i`
got `temp.i`
```c
..............
#define dsdadadassd 1
typedef struct A {
long a;
char d[1];
} A;
typedef A B;
typedef B C;
```
`symboldump temp.i` can get the origin location from line command of clang -E 's result
```bash
Location: temp.i:452:9
Presumed Location: main.h:1:9
Marco Name: foo
Content: foo 1 
--------------------------------
Location: temp.i:453:16
Presumed Location: main.h:2:16
Name: A
--------------------------------
Location: temp.i:456:3
Presumed Location: main.h:5:3
Name: A
--------------------------------
Location: temp.i:458:11
Presumed Location: ./compat.h:1:11
Name: B …
```
=> c/clang:presume location

.github/workflows/populate_linux_sysroot.sh, .github/workflows/release-build.yml
Lock to `tonistiigi/binfmt:qemu-v7.0.0-28` to avoid `binfmt` crash, see https://github.com/docker/setup-qemu-action/issues/198
See build result: https://github.com/cpunion/llgo/releases/tag/v0.9.51
=> Fix release build

compiler/cl/compile.go, compiler/cl/import.go
Fix wrong `sync.Mutex` size that cause crashes on linux.
Fix https://github.com/goplus/llgo/issues/1001
Before:
```llvm
; linux
%sync.Mutex = type { i32, i32 }
@testing.matchMutex = global %sync.Mutex zeroinitializer, align 4
; macos
%sync.Mutex = type { i64, [56 x i8] }
@testing.matchMutex = global %sync.Mutex zeroinitializer, align 8
```
After:
```llvm
; linux
@testing.matchMutex = global [48 x i8]
; macos (no changes)
%sync.Mutex = type { i64, [56 x i8] }
@testing.matchMutex = global %sync.Mutex zeroinitializer, align 8
```
=> cl: fix wrong global variable type patching

runtime/internal/lib/os/exec_posix.go
Log outputs a different Pid each time, which causes undesirable errors during comparative testing
`llgo.expect`
```bash
=> Result of llgo.expect
#stdout
.....
#stderr
StartProcess 8041 0 ((nil),(nil))
StartProcess 8042 0 ((nil),(nil))
StartProcess 8045 0 ((nil),(nil))
StartProcess 8046 0 ((nil),(nil))
#exit 0
=> Expected llgo.expect
#stdout
......
#stderr
#exit 0
2025/02/27 03:40:57 checkEqual: unexpected llgo.expect
panic: checkEqual: unexpected llgo.expect
```
=> runtime:rm log of StartProcess

_demo/defer/main.go, compiler/ssa/eh.go, runtime/internal/runtime/z_rt.go
fix defer https://github.com/goplus/llgo/issues/907
save/load defer fn and args
```
type Defer struct {
Addr unsafe.Pointer // sigjmpbuf
Bits uintptr
Link *Defer
Reth unsafe.Pointer // block address after Rethrow
Rund unsafe.Pointer // block address after RunDefers
Args unsafe.Pointer // defer func and args links
}
```
```
type node struct {
prev *node
fn   func()
args ...
}
// push
defer.Args = &node{defer.Args,fn,args...}
// pop
node := defer.Args
defer.Args = node.prev
free(node)
```
=> support defer args

.github/workflows/llgo.yml, compiler/chore/llgen/llgen_test.go, compiler/chore/llpyg/pysig/parse_test.go, compiler/cl/blocks/block_test.go, compiler/cl/builtin_test.go, compiler/cl/compile_test.go, compiler/cmd/llgo/llgo_test.go, compiler/internal/build/build.go, compiler/internal/build/build_test.go, compiler/internal/buildtags/buildtags_test.go, compiler/internal/env/env_test.go, compiler/ssa/cl_test.go, compiler/ssa/package.go, compiler/ssa/ssa_test.go, compiler/ssa/ssatest/ssautil_test.go, runtime/abi/map_test.go, test/c_test.go, xtool/clang/_types/parser/_parser_test.go
=> ci: run llgo test

.github/workflows/doc.yml, c/debug/debug.go, compiler/internal/build/build.go, runtime/internal/clite/debug/debug.go, xtool/clang/clang.go
- Can use `libunwind` instead of `llvm/libunwind` (better for WASM support)
- Can use libunwind formula on Homebrew Linux
- Better integration with Homebrew Linux (test passed on https://github.com/Homebrew/homebrew-core/pull/210790) 
- And better integration with other c toolchain
=> Remove LLVM runtime depencendy, better c toolchain integration

compiler/_lldb/README.md, compiler/_lldb/common.sh, compiler/cl/compile.go, compiler/cl/instr.go, compiler/internal/build/build.go, compiler/internal/llgen/llgenf.go, compiler/ssa/package.go
- Toggle module/func debug info with LLGO_DEBUG to enable DILocation
- Toggle variables debug info with LLGO_DEBUG_SYMBOLS, currently it has some bugs so we can only enable LLGO_DEBUG to get stacktrace with filename/line/column
=> Split debug and symbols toggle environment variables

cmd/internal/build/build.go, cmd/internal/clean/clean.go, cmd/internal/flags/flags.go, cmd/internal/install/install.go, cmd/internal/run/run.go, cmd/internal/test/test.go, internal/build/build.go, internal/build/build_test.go, internal/build/clean.go
- E.g. currently `llgo build -v -o xxx` failed
=> Fix args parsing

xtool/cppkg/command.go, xtool/cppkg/conan.go
1. conan not in apt-get ' resource,so we could not use apt-get to install conan,and use pip install will got follow error,and the suggestion in the error message tips to use pipx.
```bash
> python3 -m pip install conan
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment …
```
=> xtool/cppkg:install in linux

cl/_testgo/ifaceprom/out.ll, cl/_testrt/closurebound/in.go, cl/_testrt/closurebound/out.ll, cl/_testrt/closureconv/out.ll, cl/_testrt/intgen/out.ll, cl/import.go
fix closure func method$bound missing recv. ( `fn = v.method` )
fix https://github.com/goplus/llgo/issues/1116 https://github.com/goplus/llgo/issues/1113
=> cl: funcName check $bound

runtime/internal/clite/os/os.go, runtime/internal/clite/os/stat.go, runtime/internal/clite/os/stat_darwin.go, runtime/internal/clite/syscall/fs_wasip1.go, runtime/internal/clite/syscall/syscall.go, runtime/internal/clite/syscall/syscall_unix.go, runtime/internal/clite/syscall/syscall_wasm.go, runtime/internal/lib/os/stat_unix.go
fix https://github.com/goplus/llgo/issues/1120
- runtime/internal/clite/syscall: fix init for ErrExist...
- runtime/internal/clite/os: fix stat for macOS
=> runtime/internal/clite/syscall: fix init

internal/build/build.go, internal/crosscompile/cosscompile.go, internal/crosscompile/crosscompile_test.go, runtime/internal/clite/syscall/fs_wasm.go, runtime/internal/lib/syscall/syscall_wasm.go, xtool/clang/clang.go
TODO: Need parameters rewriting to compatible C ABI
- Build wasm with `wasip1`: `GOOS=wasip1 GOARCH=wasm llgo build -o hello.wasm .`
- Build wasm with `html/js`: `GOOS=js GOARCH=wasm llgo build -o hello.html .`
- Build wasm: `GOOS=js GOARCH=wasm llgo build -o hello.wasm .`
=> Build js/wasm with emscripten

runtime/_overlay/runtime/runtime.go
fix https://github.com/goplus/llgo/issues/1124
=> runtime: GOOS GOARCH Compiler

internal/build/build.go
with test fail,expect exit with no zero exit code.
```go
package test_test
import "testing"
func TestExample(t *testing.T) {
if 1 != 2 {
t.Fatal("1 is not equal to 2")
}
}
```
```
❯ go test     
echo $?
--- FAIL: TestExample (0.00s)
test_test.go:7: 1 is not equal to 2
FAIL
exit status 1
FAIL    github.com/goplus/llgo/_xtool/tt        0.723s
1
```
but got 
```
❯ llgo test
echo $?
--- FAIL: TestExample (0.00s)
???:1: 1 is not equal to 2
FAIL
/Users/zhangzhiyang/go/bin/tt.test: exit code 1
0
```
after update 
```
FAIL
/Users/zhangzhiyang/go/bin/tt.test: exit code 1
1
```
=> build:exit when test fail

runtime/internal/runtime/z_chan.go
=> fix:  uninitiated mutex

_demo/commandrun/commandrun.go, runtime/internal/lib/syscall/exec_libc2.go, runtime/internal/lib/syscall/exec_linux.go
The way Go calls its assembly function `libc_chdir_trampoline` via `rawSyscall` ultimately means the assembly itself just ends up calling libc's `chdir`.  So use c.Chdir directly.
=> runtime:forkAndExecInChild chdir

internal/crosscompile/cosscompile.go
generate main.js
```
// Determine the runtime environment we are in. You can customize this by
// setting the ENVIRONMENT setting at compile time (see settings.js).
// Attempt to auto-detect the environment
var ENVIRONMENT_IS_WEB = typeof window == 'object';
var ENVIRONMENT_IS_WORKER = typeof WorkerGlobalScope != 'undefined';
// N.b. Electron.js environment is simultaneously a NODE-environment, but
// also a web environment.
var ENVIRONMENT_IS_NODE = typeof process == 'object' && typeof process.versions == 'object' && typeof process.versions.node == 'string' && process.type != 'renderer';
var ENVIRONMENT_IS_SHELL = !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_NODE && !ENVIRONMENT_IS_WORKER;
```
=> GOOS=js set -sENVIRONMENT=web,worker

internal/build/build.go, runtime/internal/lib/runtime/runtime.go, ssa/expr.go, ssa/globals.go, ssa/package.go, ssa/ssa_test.go
```
runtime.Version()
runtime.GOROOT()
```
=> link globals importpath.name=value

internal/build/build.go, internal/crosscompile/cosscompile.go, internal/crosscompile/crosscompile_test.go
Based on our discussion in the meeting, the "rpath change mode" only accomplishes half of the publishing task. It is incomplete as it only modifies the library file's install_name to start with @rpath. For commands like llgo run . and llgo build ., implementing the full publishing workflow is too "heavy". Publishing should be treated as a separate solution, and therefore, this mode should be removed.
---
=> refactor(internal/build):remove rpath change

runtime/js/embind/_wrap/emval.cpp, runtime/js/emval.go, runtime/js/func.go, runtime/js/js.go
- fix call args value incref
- impl CopyBytesToGo/CopyBytesToJS
- itoa （remove strconv dep)
=> runtime/js: impl CopyBytesToGo/CopyBytesToJS

cl/_testpy/list/in.go, cl/_testpy/list/out.ll, ssa/package.go, ssa/python.go
fix https://github.com/goplus/llgo/issues/1192
- bool => PyBool
- int(in8...)/uint(uint8...) => PyLong
- float32/float64 => PyFloat
- string => PyString
- []byte => PyByteArray
- complex64/complex128 => PyComplex
- *py.Object => *Object
=> ssa: PyVal support bool,int,uint,string,complex

cl/_testpy/list/in.go, cl/_testpy/list/out.ll, ssa/python.go
PyVal support pyfunc
```
x := py.List(std.Abs, std.Print)
std.Print(x) //[<built-in function abs>, <built-in function print>]
```
=> ssa: PyVal support pyfunc

cl/_testpy/list/in.go, cl/_testpy/list/out.ll, ssa/python.go
```
a := py.List([...]byte{1, 2, 3}, [0]byte{})
std.Print(a) // [b'\x01\x02\x03', b'']
```
=> ssa: PyVal support py bytes

internal/build/build.go
The `hal` (Hardware Abstraction Layer) libraries depend on target-specific build-tags to compile the correct hardware drivers for each platform.
=> internal/build:include target build-tags in Go package compilation

internal/build/build.go
The original code used `icmp eq i32 0, 0` which always evaluates to true, resulting in argc=1:
```asm
declare i32 @printf(i8*, ...)
@fmt = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1
define i32 @main() {
entry:
%argc_val = icmp eq i32 0, 0
%argc = zext i1 %argc_val to i32
%call = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @fmt, i64 0, i64 0), i32 %argc)
ret i32 0
}
```
Output: 1 (incorrect)
After fix with add i32 0, 0, argc correctly equals 0.
=> fix: set correct argc=0 in _start() function

.github/workflows/llgo.yml, _demo/cargs/demo.go, internal/build/build.go
fixed https://github.com/goplus/llgo/issues/1135
library with conan with generate install_name directly with `@rpath` and the go is not add rpath for these dylib.
```bash
llgo/d on  internal/build/rpath [$!?] via C v17.0.0-clang 
❯ otool -D /opt/homebrew/Cellar/cjson/1.7.18/lib/libcjson_utils.dylib
/opt/homebrew/Cellar/cjson/1.7.18/lib/libcjson_utils.dylib:
/opt/homebrew/opt/cjson/lib/libcjson_utils.1.dylib
(base) 
llgo/d on  internal/build/rpath [$!?] via C v17.0.0-clang 
❯ otool -D /Users/zhangzhiyang/.conan2/p/b/cjsond2bd82ff69524/p/lib/libcjson_utils.dylib 
/Users/zhangzhiyang/.conan2/p/b/cjsond2bd82ff69524/p/lib/libcjson_utils.dylib:
@rpath/libcjson_utils.1.dylib
```
Treat every link-time library search path, specified by the -L parameter, as a runtime search path as well.This is …
=> internal/build:support relocatable lib

_demo/cabisret/main.go, internal/cabi/cabi.go
fix https://github.com/goplus/llgo/issues/1227
=> internal/cabi: fix llvm.alloca for callInsrt

cmd/internal/build/build.go, cmd/internal/flags/flags.go, cmd/internal/install/install.go, cmd/internal/run/run.go, cmd/internal/test/test.go, internal/build/build.go
move env to build -tags=dev flags
-check-linkargs
-check-llfiles
-gen-llfiles
```
LLGO_CHECK
LLGO_CHECK_LINKARGS
```
=> build: dev support checkLinkArgs/CheckLLFiles/GenLLFiles

internal/build/build.go
fix `ld64.lld: warning: duplicate -rpath '/usr/local/Cellar/bdw-gc/8.2.8/lib' ignored [--warn-duplicate-rpath]`
=> internal/build: fix warning duplicate -rpath

internal/targets/resolver.go
Replace hardcoded runtime.Caller() path calculation with env.LLGoROOT() in targets resolver for consistency with runtime directory resolution.
This aligns targets directory resolution with the existing runtime directory resolution strategy.
=> internal/target:read targets consist use LLGoROOT

.github/workflows/doc.yml, .github/workflows/fmt.yml, .github/workflows/go.yml, .github/workflows/llgo.yml, .github/workflows/release-build.yml, .github/workflows/targets.yml
This configuration automatically cancels previous running workflows when new commits are pushed to the same pull request, preventing resource waste and reducing queue times.
=> ci:concurrency config added & timeout at 30min

.github/workflows/doc.yml, .github/workflows/fmt.yml, .github/workflows/go.yml, .github/workflows/llgo.yml, .github/workflows/targets.yml
fix follow
----
Dependabot PRs trigger both push and pull_request events, causing workflows to run twice. See duplicate runs in https://github.com/luoliwoshang/llgo/pull/170. This excludes Dependabot branches from push triggers while keeping pull_request triggers intact.
you can see the result at https://github.com/luoliwoshang/llgo/pull/172，with the dependabot will only trigger the pr action
=> ci:avoid dependbot trigger reduant push event

.github/workflows/populate_linux_sysroot.sh, .github/workflows/release-build.yml
fixed https://github.com/goplus/llgo/issues/1280
The error occurred because the job below wrote incorrect cache, and subsequently read the wrong .sysroot, leading to missing linux/arm header files during the build process.
https://github.com/goplus/llgo/actions/runs/17542096574/job/49815540894
```bash
tar -czvf .sysroot/linux.tar.gz -C .sysroot linux
......
linux/amd64/lib/x86_64-linux-gnu/libz.so.1
linux/amd64/lib/x86_64-linux-gnu/libpcprofile.so
linux/arm64/
```
The root cause lies in the concurrent Docker pulling and building logic for linux arm64/amd64 when obtaining .sysroot. When Docker was started to pull linux/arm64 to get .sysroot, Docker occasionally failed to create the container, and the script did not exit properly in the background. This resulted in the missing environment …
=> ci:update .sysroot cache key & catch docker exit

cl/_testrt/vamethod/in.go, cl/_testrt/vamethod/out.ll, cl/compile.go, cl/instr.go, ssa/decl.go, ssa/type.go
fix embed struct method has `__llgo_va_list`
```
type My struct {
*py.Object
}
```
- struct embed call `__llgo_va_list`
- interface call `__llgo_va_list`
=> cl: embed struct / interface support __llgo_va_list

internal/crosscompile/crosscompile.go, internal/crosscompile/fetch_test.go
fixed https://github.com/goplus/llgo/issues/1273
with embed esp clang compile update
https://github.com/goplus/espressif-llvm-project-prebuilt/pull/22
https://github.com/goplus/espressif-llvm-project-prebuilt/pull/20
https://github.com/goplus/espressif-llvm-project-prebuilt/pull/17
https://github.com/goplus/espressif-llvm-project-prebuilt/pull/13
https://github.com/goplus/espressif-llvm-project-prebuilt/pull/9
=> internal/crosscompile:update clang with older glibc & more small size

.github/actions/setup-deps/action.yml, .github/actions/setup-goreleaser/action.yml, .github/actions/test-helloworld/action.yml, .github/workflows/download_esp_clang.sh, .github/workflows/populate_linux_sysroot.sh, .github/workflows/release-build.yml, .goreleaser.yaml, internal/crosscompile/crosscompile.go, internal/crosscompile/fetch_test.go, xtool/env/llvm/llvm.go
Resolved https://github.com/goplus/llgo/issues/1251
Release result at https://github.com/luoliwoshang/llgo/releases/tag/v0.0.1-test-espclang-5 and it's action https://github.com/luoliwoshang/llgo/actions/runs/17578939811
----
**Problem Description**
The current prebuilt LLVM libraries from [espressif-llvm-project-prebuilt v19.1.2_20250830](https://github.com/goplus/espressif-llvm-project-prebuilt/releases/tag/19.1.2_20250830) are causing linking failures due to GLIBC version incompatibility:
```bash
/usr/bin/ld: /go/src/llgo/crosscompile/clang/lib/libLLVM-19.so: undefined reference to `pthread_getname_np@GLIBC_2.34'
/usr/bin/ld: /go/src/llgo/crosscompile/clang/lib/libLLVM-19.so: undefined reference to `lstat64@GLIBC_2.33'
/usr/bin/ld: /go/src/llgo/crosscompile/clang/lib/libLLVM-19.so: …
```
=> release:compile & release with esp clang/llvm

internal/build/build.go, internal/cabi/cabi.go
call optimization:  check IR `alloca/load/store` =>  `direct ptr` / `bitcast` / `memcpy` 
transform func body
func params
func results
transform call instr
=> internal/cabi: call optimization

cl/_testrt/tpunsafe/in.go, cl/_testrt/tpunsafe/out.ll, ssa/expr.go
implement builtin `unsafe.Alignof` `unsafe.Offsetof` instance of generic function
=> ssa: impl builtin alignof offsetof

internal/build/build.go
fix
```bash
ld.lld: error: /Users/zhangzhiyang/Library/Caches/go-build/66/6632870c9c1a886cefc86ba8c27b73e755145f805c59d5666222059cd92fc1cd-d.ll:1: malformed number: ' >>> ; ModuleID = 'github.com/goplus/llgo/_demo/arr' >>> ^ exit status 1
```
=> fix:GenLL flag to correct compile

cl/_testgo/errors/out.ll, cl/_testgo/ifaceprom/out.ll, cl/_testgo/invoke/out.ll, cl/_testgo/reader/out.ll, cl/_testgo/reflect/out.ll, cl/_testgo/reflectmkfn/out.ll, cl/_testgo/struczero/out.ll, cl/_testgo/tpinst/out.ll, cl/_testrt/abinamed/out.ll, cl/_testrt/closureiface/out.ll, cl/_testrt/tpmethod/out.ll, cl/_testrt/vamethod/out.ll, ssa/abitype.go
fix interface abi load order  https://github.com/goplus/llgo/issues/1324
=> ssa: fix abiTupleOf
