goplus/llgo

- c/cjson/README.md
- c/cjson/cjson.go
> llgo/x/cjson:link cjson by pkg-config

- c/cjson/README.md
- c/sqlite/README.md
The use of cjson and sqlite in llgo will be tested in this PR
Test image：https://github.com/luoliwoshang/DockerFiles/blob/main/ubuntu/normal/Dockerfile
> 【WIP】README:cjson/sqlite download for linux

- internal/build/build.go
> build: explicitly link libpthread for compatibility with glibc versions before 2.34

- .github/workflows/go.yml
- README.md
> README,ci: add Dependencies section and update install instructions accordingly

- cl/_testdata/print/in.go
- cl/_testdata/print/out.ll
- cl/_testgo/equal/out.ll
- cl/_testgo/errors/out.ll
- cl/_testgo/ifaceconv/out.ll
- cl/_testgo/ifaceprom/out.ll
- cl/_testgo/interface/out.ll
- cl/_testgo/invoke/out.ll
- cl/_testgo/reader/out.ll
- cl/_testgo/struczero/out.ll
- cl/_testrt/eface/out.ll
- internal/runtime/z_error.go
- internal/runtime/z_face.go
- internal/runtime/z_rt.go
- ssa/abitype.go
- ssa/expr.go
- abi.Type.Str => pkgName.TypeName
- panic any custom type
> runtime: panic any custometype

- c/raylib/_demo/tetris/tetris.go
- c/raylib/raylib.go
- c/raylib/shape.go
> llgo/c/raylib:tetris demo

- cl/_testlibgo/bytes/in.go
- cl/_testlibgo/bytes/out.ll
- cl/_testlibgo/strings/in.go
- cl/_testlibgo/strings/out.ll
- cl/_testrt/builtin/out.ll
- internal/lib/internal/bytealg/bytealg.go
- ssa/datastruct.go
- ssa: fix slice high
- internal/lib/internal/bytealg: count index
- cl/_testlibgo: bytes strings
> ssa fix slice high, update bytealg for pkg bytes/strings

- ssa/abitype.go
> ssa: fix abi patch types.pointer

- c/c.go
Add two functions ：Fopen &  Fclose
> feat(llgo/c):Add two functions : Fopen &  Fclose

- c/zlib/README.md
> [wip] README:zlib

- README.md
- cl/compile_test.go
This also cleans up the remaining mentioned LLGOROOT.
> readme: simplify installation instructions

- .github/workflows/populate_darwin_sysroot.sh
- .github/workflows/populate_linux_sysroot.sh
- .github/workflows/release-build.yml
- .gitignore
- .goreleaser.yaml
```sh
bash .github/workflows/populate_darwin_sysroot.sh
bash .github/workflows/populate_linux_sysroot.sh
```
```sh
docker run \
--rm \
-v /var/run/docker.sock:/var/run/docker.sock \
-v $(pwd):/go/src/llgo \
-w /go/src/llgo \
ghcr.io/goreleaser/goreleaser-cross:v1.22 \
release --clean --skip nfpm,snapcraft --snapshot --verbose
```
> ci: implement release-build.yml workflow with GoReleaser

- _demo/socket/server/server.go
- c/socket/socket.go
The service running on server.go can properly receive messages and has been tested with a client written in C language.
> llgo/c/socket:server demo

- _demo/socket/client/client.go
> llgo/c/socket:client demo

- xtool/env/env.go
> limit expand env to cmd pkg-config & llvm-config

- c/c.go
- x/io/_demo/asyncdemo/async.go
- x/io/io.go
https://github.com/goplus/llgo/issues/545
> llgo/x/io: Promise: Async/Await

- c/libuv/_demo/async_fs/async_fs.go
- c/libuv/fs.go
- c/libuv/libuv.go
Signed-off-by: hackerchai <i@hackerchai.com>
> fix(c/libuv): Fix return type FsType & struct rename

- internal/build/build.go
- ssa/eh.go
- ssa/package.go
> ssa: fix `Builder.Sigsetjmp` for Linux

- .github/workflows/go.yml
- .github/workflows/test_demo.sh
Achieved 100% pass rate for demo tests, at least on macOS.
> ci: install further optional dependencies for demos

- doc/How-to-support-a-C&C++-Library.md
1. Added correct usage examples for destructors
2. Moved the destructor description and examples to follow the constructor section, improving the document structure
For handling implicit constructors, the document now refers to examples using `std::string`
This change was made because in the actual INIReader examples, all constructors are explicitly exposed, and there are no cases requiring users to manually call implicit constructors
> doc/c: fix incorrect Constructor and Destructor usage in bindings

- c/libuv/_demo/echo_server/echo_server.go
- c/libuv/libuv.go
- c/libuv/net.go
- c/libuv/timer.go
Handle, Stream are the parent classes of Tcp and should be placed under net.
> refactor(c-libuv): Added TODO(uid) comment & adjusted the position of Handle, Stream, Req, Write, Connect

- c/clang/_demo/symboldump/symboldump.go
- c/clang/_wrap/cursor.cpp
- c/clang/clang.go
Marco content may not be exported at this time
> [wip] c/clang:marco info

- cl/_testgo/equal/out.ll
- cl/_testrt/makemap/in.go
- cl/_testrt/makemap/out.ll
- cl/_testrt/map/out.ll
- ssa/abitype.go
fix https://github.com/goplus/llgo/issues/664
> ssa: fix abi map init

- cl/compile.go
fix https://github.com/goplus/llgo/issues/668
> cl: build initAfter

- cl/_testgo/tpindex/out.ll
- cl/_testgo/tprecur/out.ll
- cl/_testgo/tptypes/out.ll
- cl/_testrt/tpabi/in.go
- cl/_testrt/tpabi/out.ll
- cl/compile.go
- cl/import.go
- cl/instr.go
- ssa/abi/abi.go
- ssa/abitype.go
- ssa/decl.go
- ssa/type.go
fix https://github.com/goplus/llgo/issues/668
> cl: makeInterface check instance named

- internal/lib/os/os.go
support `Mkdir`,`MkdirAll`,`MkdirTemp` #709 
In Go, `FileMode` is a 32-bit integer where:
* The highest 12 bits represent file types and special attributes (such as directory, symlink, etc.)
* The middle 11 bits are currently unused and reserved for future expansion
* The lowest 9 bits represent Unix-style permissions (read, write, execute permissions)
Meanwhile, `ModeT` is represented in 16 bits. Unlike Go's 32-bit FileMode, ModeT uses a more compact structure.
The`fileModeToUnixMode` function in `src/archive/zip/struct.go` converts `FileMode` to the `ModeT` format as a uint32:
```go
func fileModeToUnixMode(mode fs.FileMode) uint32 {
var m uint32
switch mode & fs.ModeType {
default:
m = s_IFREG
case fs.ModeDir:
m = s_IFDIR
case fs.ModeSymlink:
m = s_IFLNK
case fs.ModeNamedPipe:
m = …
```
> lib/os:fileMode to ModeT , `Mkdir` run normally

- _demo/mkdirdemo/mkdir.go
- internal/lib/os/os.go
> lib/os:fix error fileMode to ModeT

- chore/llcppg/ast/ast.go
**IsConst** : const member function
**Access** :  access level
```cpp
class INIReader {
public:
INI_API int ParseError() const; 
}
```
> llcppg/ast:func decl

- cl/_testgo/tpnamed/in.go
- cl/_testgo/tpnamed/out.ll
- ssa/type_cvt.go
fix https://github.com/goplus/llgo/issues/759
> ssa: cvtNamed check typeargs

- cl/_testdata/llgotag/in.go
- cl/_testdata/llgotag/out.ll
- internal/build/build.go
Fix https://github.com/goplus/llgo/issues/412
> cl: builtin llgo tag

- cl/_testgo/selects/in.go
- cl/_testgo/selects/out.ll
- internal/runtime/z_chan.go
fix https://github.com/goplus/llgo/issues/742
> runtime: fix multi chan recv/send select

- chore/_xtool/llcppsymg/parse/parse.go
> llcppsymg:filter public method

- cl/_testrt/len/in.go
- cl/_testrt/len/out.ll
- cl/_testrt/makemap/out.ll
- internal/runtime/z_chan.go
- internal/runtime/z_map.go
- ssa/datastruct.go
- ssa/expr.go
fix https://github.com/goplus/llgo/issues/808
> runtime: fix map len and chan len/cap

- cl/_testgo/equal/out.ll
- cl/_testgo/errors/out.ll
- cl/_testgo/ifaceprom/out.ll
- cl/_testgo/interface/out.ll
- cl/_testgo/invoke/out.ll
- cl/_testgo/reader/out.ll
- cl/_testgo/strucintf/out.ll
- cl/_testgo/struczero/out.ll
- cl/_testrt/abinamed/out.ll
- cl/_testrt/any/out.ll
- cl/_testrt/eface/out.ll
- cl/_testrt/funcdecl/out.ll
- cl/_testrt/len/out.ll
- cl/_testrt/makemap/out.ll
- cl/_testrt/map/out.ll
- cl/_testrt/tpabi/out.ll
- cl/_testrt/tpmethod/out.ll
- ssa/abitype.go
- ssa/package.go
fix internal/lib/reflect.rtype assert to interface Type method type load order.
> ssa: abi check interface method

- cl/_testrt/freevars/in.go
- cl/_testrt/freevars/out.ll
- ssa/decl.go
fix https://github.com/goplus/llgo/issues/774
> cl: function fix freevars cache

- chore/_xtool/llcppsymg/_cmptest/args_test/args.go
- chore/_xtool/llcppsymg/_cmptest/args_test/llgo.expect
- chore/_xtool/llcppsymg/args/args.go
For get the base flags of llcppsymg & llcppsigfetch
llcppsigfetch & llcppsymg https://github.com/goplus/llgo/pull/812,https://github.com/goplus/llgo/pull/788 is use it now.
> llcppsymg & llcppsigfetch parse args

- cl/_testgo/invoke/out.ll
- cl/_testrt/closureiface/out.ll
- cl/_testrt/eface/out.ll
- cl/_testrt/funcdecl/out.ll
- internal/abi/type.go
- internal/lib/reflect/value.go
- internal/runtime/z_face.go
- ssa/interface.go
- x/ffi/ffi.go
internal/abi: `TFlagClosure`
internal/lib/reflect: `flagClosure`
> [WIP]  internal/lib/reflect: implement reflect.call

- cl/_testrt/slicelen/in.go
- cl/_testrt/slicelen/out.ll
- ssa/expr.go
fix #848 
https://github.com/goplus/llgo/pull/849 This More complex demo can run normally by this pr
> ssa:fit unsafe.slice int size

- cl/_testgo/reflect/in.go
- cl/_testgo/reflect/out.ll
- cl/_testrt/abinamed/out.ll
- internal/abi/type.go
- internal/lib/reflect/makefunc.go
- internal/lib/reflect/type.go
- internal/lib/reflect/value.go
internal/lib/reflect:
- typeof for closure
- call func
- call method
- call in typ => ffi
- call multi ret
- makeMethodValue
- Value.NumField
- Value.Field
- Value.Bool
- Value.Float
- Value.bytesSlow
- Value.Len
- Value.Cap
- Value.SetLen
- Value.SetCap
- Value.Slice
- Value.Slice3
- Value.UnsafePointer
- Value.New
- Value.SetZero
- Value.isZero
- Value.InterfaceData
> internal/lib/reflect: support method call

- .github/workflows/doc.yml
- .github/workflows/go.yml
Fix https://github.com/goplus/llgo/actions/runs/11984792390/job/33415974809
> ci: remove pre-installed pkg-config

- cpp/llvm/llvm.go
> fix: wrong llvm libs flag

- xtool/env/env.go
> xtool/env: fix ExpandEnvToArgs check pkg-config

- internal/build/build.go
env set `LLGO_CHECK=1`
check pkg by `llc -filetype=null input.ll`
> [WIP] build: env LLGO_CHECK=1 for llc check module

- README.md
> README: add install instructions for Alpine

- cl/_testgo/cgocfiles/out.ll
- cl/_testgo/equal/out.ll
- cl/_testgo/errors/out.ll
- cl/_testgo/ifaceconv/out.ll
- cl/_testgo/ifaceprom/out.ll
- cl/_testgo/interface/out.ll
- cl/_testgo/invoke/out.ll
- cl/_testgo/reader/out.ll
- cl/_testgo/reflect/out.ll
- cl/_testgo/struczero/out.ll
- cl/_testrt/abinamed/out.ll
- cl/_testrt/eface/out.ll
- cl/_testrt/makemap/out.ll
- cl/_testrt/tpabi/out.ll
- cl/_testrt/tpmap/out.ll
- cl/_testrt/tpmethod/out.ll
- cl/_testrt/typed/out.ll
- internal/lib/reflect/makefunc.go
- internal/runtime/z_face.go
- internal/runtime/z_type.go
- ssa/abitype.go
- named preset str and uncommon pkgpath
- named ptr check uncommon type  if has methods.
- cache typelist
- funcStr 
- interfaceStr 
- structStr
- array index str
> [WIP] internal/runtime: named(ptr) type preset for method type

- internal/runtime/z_face.go
- internal/runtime/z_type.go
- impl abi.Type.Hash
reference `typeutil.Hasher` https://github.com/goplus/llgo/blob/main/internal/typeutil/map.go#L208
Different implement
types.Named : 9157 + hasString(typ.Uncommon().PkgPath_)+ hashString(typ.Str_)
> [WIP] internal/runtime: type hash

- internal/build/build.go
When `github.com/goplus/llgo` is imported in go.mod, use the user-specified version instead of LLGoROOT. This allows users to upgrade llgo via go.mod while maintaining backward compatibility for cases without explicit imports.
Note: This is a temporary solution. The runtime's dependency on github.com/goplus/llgo/c/* needs to be addressed in future improvements.
> build: make llgo root usage optional for runtime loading

- compiler/cl/_testrt/namedslice/in.go
- compiler/cl/_testrt/namedslice/out.ll
- compiler/cl/compile.go
fix named slice type
```
package main
type MyBytes []byte
func main() {
var i any = MyBytes{} // bad type to []byte
_, ok := i.(MyBytes)
if !ok {
panic("bad slice")
}
}
```
> compiler/cl: fix named slice type

- .goreleaser.yaml
Fix https://github.com/goplus/llgo/issues/971
> build: fix goreleaser env injection

- runtime/internal/lib/internal/reflectlite/type.go
- runtime/internal/lib/internal/reflectlite/value.go
- runtime/internal/lib/reflect/type.go
- reflect.Type.Implements
- reflectlite implement todo func
> runtime/internal/lib/reflectlite: implement func

- runtime/internal/lib/time/sleep.go
Fix https://github.com/goplus/llgo/issues/999
> runtime: fix time.Sleep

- compiler/internal/build/build.go
Supports https://github.com/goplus/llgo/issues/1017
> link: don't run install_name_tool -change by default

- cl/_testgo/runtest/main_test.go
- internal/build/build.go
fix https://github.com/goplus/llgo/issues/1150
> internal/build:switch workdir from testpkg like go behavior

- runtime/internal/clite/debug/_wrap/debug_wasm.c
- runtime/internal/clite/debug/debug.go
- runtime/internal/clite/debug/debug_wasm.go
- runtime/internal/runtime/z_rt.go
- fix panic for wasm  ( loop 'not implemented`)
- print stack for wasm
- emscript: support for EM_ASM
- wasi: none
> debug: fix print stack for wasm

- cl/_testpy/list/in.go
- cl/_testpy/list/out.ll
- ssa/python.go
types.UnsafePointer/types.Pointer => py.long
> ssa: PyVal support pointer to long
